version: '3.8'

services:
  paradigmas:
    image: dmstr/php-yii2:latest-nginx
    container_name: web_idea
    ports:
      - "8090:80"
    volumes:
      - ./web_idea:/app/web
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
